config/routes.rb
RssReader::Application.routes.draw do

  get "to_reads/create"
  get "to_reads/destroy"
  get "user_read_items/destroy"
  resources :sessions, :feeds, :feed_user_categories
  resources :items do
    member do
      get 'read'
    end
  end
  resources :user_categories do
    collection { post :sort }
  end
  resources :users do
    collection { post :sort}
    member do
      get 'change_password'
    end
  end

  root :to => 'items#index'

  get "profile" => "users#edit", :as => "profile"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "/auth/:provider/callback" => "sessions#authenticate"
  get "/signout" => "sessions#destroy", :as => :signout

end

app/views/shared/_renderFlash.html.erb
<% flash.each do |t, msg| %>
  <div class="alert <%= bootstrap_class_for(t) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_renderSessionControls.html.slim
- if current_user 
  li.white
    /padding is set to override bootstrap :C
    a href="#{edit_user_path(current_user)}" style="padding-top: 0px; padding-bottom: 0px;"
      img.avatar src="#{current_user.avatar}"
      | #{h current_user.first_name} #{h current_user.last_name}
  li.divider-vertical
  li == link_to 'Log out', log_out_path
- else
  li == link_to 'Sign Up', sign_up_path()
  /li == link_to  'Log In',  log_in_path()
  li == link_to  'Log In',  '#loginForm', :data => {:toggle=>"modal"}

   
  / Modal
  #loginForm.modal.hide.fade tabindex='-1' role='dialog' aria-labelledby='loginFormLabel' aria-hidden='true'
    .modal-header
      button type='button' class='close' data-dismiss='modal' aria-hidden='true' ×
      h3#loginFormLabel Log In
    == form_tag sessions_path do
      .modal-body
        p
          == label_tag :email
          br
          == text_field_tag :email, params[:email], :autofocus => true
        p
          == label_tag :password
          br
          == password_field_tag :password
      .modal-footer
        == link_to "Sign in with Facebook", "/auth/facebook", :class => "btn"
        == submit_tag "Log in", :class => "btn btn-primary"