config/routes.rb
RssReader::Application.routes.draw do

  get "to_reads/create"
  get "to_reads/destroy"
  get "user_read_items/destroy"
  resources :sessions, :feeds, :feed_user_categories
  resources :items do
    member do
      get 'read'
    end
  end
  resources :user_categories do
    collection { post :sort }
  end
  resources :users do
    collection { post :sort}
    member do
      get 'change_password'
    end
  end

  root :to => 'items#index'

  get "profile" => "users#edit", :as => "profile"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "/auth/:provider/callback" => "sessions#authenticate"
  get "/signout" => "sessions#destroy", :as => :signout

end

app/models/item.rb
require 'rinku'

class Item < ActiveRecord::Base
  
  #Order
  #default_scope :order => 'created_at DESC'
  default_scope :order => 'id DESC' #faster and almost equivalent
  
  #Validations
  #  presence
  validates :title, :link, :presence => true
  #  uniqueness
  validates :title, :uniqueness => true
  validates :link, :uniqueness => true

  #Relations
  has_many :users
  has_many :user_read_items
  has_many :users, :through => :user_read_items
  belongs_to :feed
  
  #Integrity Checks
  # before_save :new_entry_check
  #
  before_save do |i|
    begin
      #sanitize
      i.title       = ActionController::Base.helpers.sanitize i.title
      i.description = '' if !i.description
      i.description = ActionController::Base.helpers.sanitize i.description

      #linkify
      i.description = Rinku.auto_link(i.description, :all, 'target="_blank"')
    rescue Exception
      #TODO: Display error on this Item creation to user UTF format error!!
      return false
    end
    return true
  end

  def self.getItems(userID, userCatID, feedID, read, later)

    puts "%%%%%%%%%%%%%%% getItems(uID:#{userID}, uCat:#{userCatID}, fID:#{feedID}, read:#{read}, later:#{later})"

    sqlStr ="
      SELECT distinct
        i.id
        ,i.title
        ,i.link
        ,i.abstract
        ,i.description
        ,i.created_at
        ,i.updated_at
        ,i.image_url
        ,i.feed_id
      FROM
        items i"

    sqlStr << "
        JOIN feeds f                  ON f.id        = i.feed_id
        JOIN feed_user_categories fuc ON fuc.feed_id = f.id
        JOIN user_categories uc       ON uc.id       = fuc.user_category_id
        JOIN users u                  ON u.id        = uc.user_id
      WHERE
        u.id = #{userID}"

    sqlStr << " AND uc.id      = #{userCatID}" if userCatID
    sqlStr << " AND i.feed_id  = #{feedID}"    if feedID

    unless read.nil?
      readCond = ""
      readCond = "NOT" if read=="0"

      puts "read:#{read}"

      sqlStr << " AND i.id #{readCond} IN
                    (
                      SELECT item_id
                      FROM user_read_items
                      WHERE user_id = #{userID}
                    )
      "
    end

    unless later.nil?
      readCond = ""
      readCond = "NOT" if later=="0"

      puts "later:#{later}"

      sqlStr << " AND i.id #{readCond} IN
                    (
                      SELECT item_id
                      FROM to_reads
                      WHERE user_id = #{userID}
                    )
      "
    end


    sqlStr  << " ORDER BY i.created_at"

    self.find_by_sql(sqlStr)
  end
  
  def self.getFeedItems(feedID)
    sqlStr ="
    SELECT distinct
      i.id
      ,i.title
      ,i.link
      ,i.abstract
      ,i.description
      ,i.created_at
      ,i.updated_at
      ,i.image_url
      ,i.feed_id
    FROM
      items i"
    unless feedID.nil?
      sqlStr << "  
    WHERE
      i.feed_id = #{feedID}"
    end
    self.find_by_sql(sqlStr)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:show, :read, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index

    unless current_user
      @title = "Latest News"
      @items = Item.getFeedItems(params[:feed_id])
      return
    end
    
    #current_user exists
    cat = params[:category_id]
    fID = params[:feed_id]
    
    #Menu
    @ucat  = user_categories.find_by_id(cat)
    #Content
    name = ""
    name = @ucat.name unless @ucat.nil?
    cFeed = Feed.find_by_id(fID)
    @title = "Latest #{name} News"
    
    unless cFeed.nil?
      unless cFeed.name.nil?
        if cFeed.name.length > 1
          @title << " from '#{cFeed.name}'"
        end
      end
    end
    
    @items = user_items

    respond_to do |format|
      format.html
      format.json { render json: @items}
    end

  end

  # GET /items/1
  # GET /items/1.json
  def show
    
    if current_user
      fueLeido = false
      UserReadItem.all.each do |uri|
        if uri.user_id == current_user.id && uri.item_id.to_s == params[:id]
          fueLeido = true
        end
      end
      if !fueLeido
        UserReadItem.create(:user_id=> current_user.id, :item_id => params[:id])
      end
  
      #leerDespues = false #unused..
      ToRead.all.each do |tr|
        if tr.user_id == current_user.id && tr.item_id.to_s == params[:id]
          ToRead.find(tr.id).destroy
        end
      end
    end

    respond_to do |format|
      format.html
      format.json { render json: @item}
    end
    
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  def read
    show
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      begin
        @item = Item.find(params[:id])
      rescue Exception
        redirect_to items_url, :notice => "Item not found :C, our monkeys are working on it!"
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :link, :abstract, :description, :feed_id)
    end


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br />
    <%= f.text_area :abstract %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'addCategory-buttonLink' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item, {:class=>"category-buttonLink"} %> |
<%= link_to 'Back', items_path, {:class=>"category-buttonLink"}%>

app/views/items/index.html.slim
- content_for :actions do
  - if current_user && params[:category_id]
    li == link_to 'Add Feed', new_feed_path(:category_id => params[:category_id])
    li == link_to 'Edit Category', edit_user_category_path(:id => params[:category_id])
    li == link_to 'Delete Category', {:controller => "user_categories", :action => 'destroy', :id => params[:category_id]},:confirm => "Estas seguro?", :method => :delete


h3
  ==@title


- unless current_user && params[:category_id]
  h5 En esta pagina aparecen todas las noticias de los Feeds que el usuario haya agregado

-if @items.empty?
  p No news right now :C

/#items data-items="#{ json_for @items}"
#items
  -@items.each do |item|
    .media
      -if current_user
        /using where, limit1
          - uReadItem = UserReadItem.where("user_id = ?  AND item_id = ?", current_user.id, item.id).limit(1)
          - trItem    = ToRead.where("      user_id = ?  AND item_id = ?", current_user.id, item.id).limit(1)
          - if uReadItem.to_s.strip.length == 0
            /unread
            == image_tag 'http://ico.io/glyphicons_free/glyphicons/png/glyphicons_266_flag.png', :title => 'To read', :alt => 'To read'
          - else
            /read
            == link_to 'Mark as Unread', :controller => 'user_read_items', :action => 'destroy',:id => uReadItem, :method => :delete
          
        - fueLeido=false
        - uriID=1
        - UserReadItem.all.each do |uri|
          - if uri.user_id == current_user.id && uri.item_id == item.id
            - fueLeido = true
            - uriID    = uri.id
        /Revisa la tabla de ToRead y decide si esta en "leer despues"
        - leerDespues = false
        - trID = 1
        - ToRead.all.each do |tr|
          - if tr.user_id == current_user.id && tr.item_id == item.id
            - leerDespues = true
            - trID        = tr.id
        
        
        /read status
        a.pull-left href="#"
          -if leerDespues
            == image_tag 'http://ico.io/glyphicons_free/glyphicons/png/glyphicons_266_flag.png', :title => 'To read', :alt => 'To read'
        
        
          /-if fueLeido
            h5.pull-right
              /markUnread EyeClose
              == link_to raw(image_tag 'http://ico.io/glyphicons_free/glyphicons/png/glyphicons_052_eye_close.png', :title => 'Mark as Unread', :alt => 'Mark as Unread'), :controller => 'user_read_items', :action => 'destroy',:id => uriID, :method => :delete
          /-else
            -if leerDespues
              h5.pull-right
                /toRead FLAG
              == image_tag 'http://ico.io/glyphicons_free/glyphicons/png/glyphicons_266_flag.png', :title => 'To read', :alt => 'To read'
            -else
              h5.pull-right
                /readLater text
                == link_to 'Read Later', :controller => 'to_reads', :action => 'create',:item_id => item.id, :method => :post
        
      .strong.pull-right
        p id = "leido_id_#{uriID}"
          == "#{time_ago_in_words item.created_at.localtime} ago"
      .strong.pull-right
        p
        - if !leerDespues
          -if fueLeido
            a data-remote="true" id="leido_id_#{uriID}" href="/user_read_items/destroy?method=delete&uri_id=#{uriID}" onclick="borrarLeido(#{uriID}, 'already', #{item.id})" <img alt="Mark as Unread" src="http://ico.io/glyphicons_free/glyphicons/png/glyphicons_052_eye_close.png" title="Mark as Unread" />
            /== link_to raw(image_tag 'http://ico.io/glyphicons_free/glyphicons/png/glyphicons_052_eye_close.png', :title => 'Mark as Unread', :alt => 'Mark as Unread'), :controller => 'user_read_items', :action => 'destroy',:uri_id => uriID, :method => :delete
          -else
            a  data-remote="true" id="later_#{item.id}" href="/to_reads/create?method=post&item_id=#{item.id}" onclick="later(#{item.id})" <img alt="Read Later" src="http://ico.io/glyphicons_free/glyphicons/png/glyphicons_072_bookmark.png" title="Read Later" />
            /== link_to raw(image_tag 'http://ico.io/glyphicons_free/glyphicons/png/glyphicons_072_bookmark.png', :title => 'Read Later', :alt => 'Read Later'), :controller => 'to_reads', :action => 'create',:item_id => item.id, :method => :post
      .media-body
        h4.media-heading id = "leido_id_#{uriID}"
          ==link_to item.title, item
        p id = "leido_id_#{uriID}"
          - if item.abstract.nil?
            /== link_to truncate(strip_tags(sanitize(item.description.gsub(/&nbsp;/i,' '))), :length => 90), item
            == link_to truncate(raw(CGI.unescapeHTML(strip_tags(item.description))), :length => 90), item
          - else
            == link_to truncate(raw(CGI.unescapeHTML(strip_tags(item.abstract))), :length => 90), item

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/read.html.slim
- content_for :actions do
  - if current_user
    li == link_to 'Read Original', @item.link, { :class=>"category-buttonLink", :target => '_blank' }
    li == link_to 'Back', item_path(@item), { :class=>"category-buttonLink"}

iframe.container.well.span12 src="#{@item.link}" position="absolute" top="0" bottom="0" style="min-height:100%;"

app/views/items/show.html.slim
- content_for :actions do
  li == link_to 'Read more', read_item_url(@item)
  li == link_to 'Back', items_path
  /:category_id => ucat.id
  - if current_user && current_user.is_admin?
    li == link_to 'Edit', edit_item_path(@item)

//

h2 #{@item.title}
p style="text-align:right;"  #{time_ago_in_words @item.created_at.localtime} ago

hr


- if @item.image_url
  == image_tag @item.image_url, :class => 'img-rounded'
p
  - if @item.description.to_s.length >0
    == @item.description
  - else
    == @item.abstract

hr

p
  == link_to 'Read more', read_item_url(@item), :class => "btn"

  label.uiButton.uiButtonLarge.uiButtonConfirm
    input value="Share on Facebook" onclick="postToFeed(); return false;" type="submit"

hr
.span12
  .fb-comments data-href="#{request.protocol}#{request.host_with_port}#{request.fullpath}" data-width="550" data-num-posts="10"