config/routes.rb
RssReader::Application.routes.draw do

  get "to_reads/create"
  get "to_reads/destroy"
  get "user_read_items/destroy"
  resources :sessions, :feeds, :feed_user_categories
  resources :items do
    member do
      get 'read'
    end
  end
  resources :user_categories do
    collection { post :sort }
  end
  resources :users do
    collection { post :sort}
    member do
      get 'change_password'
    end
  end

  root :to => 'items#index'

  get "profile" => "users#edit", :as => "profile"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "/auth/:provider/callback" => "sessions#authenticate"
  get "/signout" => "sessions#destroy", :as => :signout

end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Feed Readr

    /link rel="icon" type="image/x-icon" href="http://ico.io/glyphicons_free/glyphicons/png/glyphicons_397_rss.png"
    link rel="icon" type="image/x-icon" href="http://freader.herokuapp.com/feedReader_128x128.png"
    == csrf_meta_tags

    /JS
    == yield :js
    == javascript_include_tag '//connect.facebook.net/en_US/all.js'
    == javascript_include_tag '//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js'
    == javascript_include_tag :defaults
    == javascript_include_tag "application", "data-turbolinks-track" => true


    /CSS
    == yield :css
    == stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    == stylesheet_link_tag '//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css'


  body
    
    / Layout
        Header
        -Actions
        -Session
        Container
        -Menu
        __Categories
        -Content

    #fb-root
    /javascript:
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=536164159776235";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
      FB.init({appId: "536164159776235", status: true, cookie: true});
    .container
      .navbar.navbar-inverse
      
        .navbar-inner.nav-collapse style='height:auto;'
          ul.nav
            li.active
            a.brand href="#{root_path}" Feed Reader
          ul.nav.nav-center
            == yield :actions
          
          /Session Management
          ul.nav.pull-right
            == render "shared/renderSessionControls"
          
      .content.row-fluid
        .span3.sidebar
          - if current_user
            
            h4 Category Management
            ul.nav.nav-tabs.nav-stacked
              li == link_to '+ Category', new_user_category_path
            
            h4 Important Stuff
            ul.nav.nav-tabs.nav-stacked
              li == link_to 'All', items_path
              li.divider
              li == link_to 'Read Later', items_path(:later => 1)
              li == link_to 'Unread', items_path(:read => 0)
              li == link_to 'Already Read', items_path(:read => 1)
            
            - if user_categories.count>0
            
              h4 Categories
              - user_categories.find_each do |ucat|
              
                .btn-group.btn-block.fillsplit
                  .leadcontainer
                    a.btn.btn-primary.dropdown-lead href="#{items_path(:category_id => ucat.id)}"
                      = "#{ucat[:name]} "
                  
                  a.btn.btn-primary.dropdown-toggle data-toggle="dropdown"
                    span.caret

                  ul.dropdown-menu.right
                    /Default
                    li
                      a href="#{items_path(:category_id => ucat.id)}" View Category
                    /Feeds
                    li.divider
                    li.nav-header View Feed
                    - FeedUserCategory.all.each do |f|
                      - if f.user_category_id == ucat.id
                        li
                          a href="#{items_path(:category_id => ucat.id, :feed_id => f.feed_id)}"
                            i.icon-rss
                            = "#{Feed.find(f.feed_id).name || 'Unammed Feed'}"
                    /Actions
                    li.divider
                    li.nav-header Customize Category
                    li
                      a href="#{new_feed_path(:category_id => ucat.id)}"
                        i.icon-plus-sign
                        | Add Feed
                    li
                      a href="#{edit_user_category_path(:id => ucat.id)}"
                        i.icon-pencil
                        | Edit
                    li
                      /ugly as hell :C
                      == link_to raw('<i class=\'icon-trash\'></i>Delete'), {:controller => "user_categories", :action => 'destroy', :id => ucat.id},:confirm => "Estas seguro?", :method => :delete
                br
            - else
              h4 No categories :C
              h5 Add a new one!
          - else
            h4 Log in to customize your news!
            ul.nav.nav-tabs.nav-stacked
              - Feed.all.each do |f|
                li == link_to "#{f.name || 'Unammed Feed'}", items_path(:feed_id => f.id)
        
        
        
        .span9.main.well position="absolute" top="0" bottom="0" style="min-height:100%;"
          == render "shared/renderFlash"
          == yield